version: '3.9'

services:
  # Django application
  web:
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT:-8000}
    environment:
      - DJANGO_PORT=8000
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # Database (PostgreSQL)
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  # Redis (Celery broker)
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Celery worker
  celery_worker:
    container_name: celery_worker
    build: ./
    command: celery -A Weather_reminder worker --loglevel=INFO
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      -  web
